### ISSUE TITLE
more validations in minimesos script

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/mini-mesos#110]
The ```/usr/local/bin/minimesos``` script should check if ```java``` matches the minimum JDK (or JRE) requirements

**Comment by sadovnikov** [comment]
the script is taken from http://minimesos.org/install

**Comment by frankscholten** [comment]
We will run it in Docker to deal with this issue. See https://github.com/ContainerSolutions/mini-mesos/issues/107

**Comment by sadovnikov** [comment]
closing as duplicate for #107
