### ISSUE TITLE
R&D replacing container echo with docker wait 

### ISSUE THREAD

**Issue by frankscholten** [ContainerSolutions/mini-mesos#28]
Right now we run a docker exec that returns echo to check whether a container is running. Let's look if we can replace it with a docker wait command.

**Comment by frankscholten** [comment]
Docker wait is not the right tool to use because it's for waiting until a container is stopped. Instead let's list the containers periodically and check if the container ID is in the list.

**Comment by philwinder** [comment]
I did something very similar here. You can probably copy paste.
https://github.com/mesos/elasticsearch/blob/enhancement/%23167-Executor-heap/system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/ExecutorSystemTest.java#L40
