### ISSUE TITLE
Write container logs on failure

### ISSUE THREAD

**Issue by frankscholten** [ContainerSolutions/mini-mesos#32]

**Comment by frankscholten** [comment]
We currently write out all the containers logs before the cluster stops. This leads to a lot of log files. It's better to only log on failure

**Comment by mwl** [comment]
For at start we could write it to a tmp dir out of version control

**Comment by frankscholten** [comment]
Logs are written to logger on failure https://github.com/ContainerSolutions/mini-mesos/pull/54

**Comment by frankscholten** [comment]
Yes let's stop writing log files. I'll add a new issue.
