### ISSUE TITLE
Using mini-mesos container with marathon container

### ISSUE THREAD

**Issue by rossf7** [ContainerSolutions/mini-mesos#38]
We're working on a scheduler written in Go that runs on top of Marathon and call its REST API. At the moment for development we're using a single CoreOS VM running Mesos, Marathon and Zookeeper containers.

We were wondering if its possible to use Docker Compose to link a mini-mesos container to a marathon container. We could then add our scheduler container and have a more lightweight development environment.

Is this possible at the moment or on your roadmap? Happy to help with testing if needed.

Thanks

Ross

**Comment by frankscholten** [comment]
Are you planning to write system tests in Java / JUnit or do you only like to run Mini Mesos's container?

There are several ways Marathon can be integrated

* Link Marathon via Docker compose to the Mini Mesos's mesos-local container: https://github.com/ContainerSolutions/mesos-local
* Create a Marathon container by extending Mini Mesos's https://github.com/ContainerSolutions/mini-mesos/blob/master/src/main/java/org/apache/mesos/mini/container/AbstractContainer.java and use it inside a JUnit test
* Add Marathon to the mesos-local image Docker image as a separate process under supervisor.

**Comment by rossf7** [comment]
Yes we'd like to run a Marathon container in front of Mini Mesos. We can then write our tests in Go and have a local Mesos and Marathon environment to run on top of.

I've had a go and managed to get it working. Here are the Docker Compose and .env files I'm using.

```
# docker-compose.yml

marathon:
  image: mesosphere/marathon:v0.9.0
  command: "--master zk://mesos:2181/mesos --zk zk://mesos:2181/marathon"
  links:
    - mesos
  ports:
    - "8080:8080"
mesos:
  env_file: .env
  privileged: true
  image: containersol/mesos-local
  ports:
    - "5050:5050"
  expose:
    - "2181"
  volumes:
    - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
```

```
# .env

NUMBER_OF_SLAVES=2
MESOS_QUORUM=1
MESOS_ZK=zk://localhost:2181/mesos
MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
MESOS_CONTAINERIZERS=docker,mesos
MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
MESOS_LOG_DIR=/var/log
SLAVE1_RESOURCES=ports(*):[9200-9200,9300-9300]
SLAVE2_RESOURCES=ports(*):[9201-9201,9301-9301]
```

Thanks again for developing this! Its going to be really useful for our Force12 project.

Cheers

Ross
