### ISSUE TITLE
MesosCluster::injectImage should support image tags

### ISSUE THREAD

**Issue by FlorianGrundig** [ContainerSolutions/mini-mesos#39]
Injecting a docker images with a special tag is currently not supported. This is quite important when you want to run your system tests against a tagged executor (e.g. before I push the docker image to docker hub).

**Comment by philwinder** [comment]
Can't you retag it after you have tested it? That's what I do.

On 5 Aug 2015 8:11 am, Florian Grundig <notifications@github.com> wrote:

Injecting a docker images with a special tag is currently not supported. This is quite important when you want to run your system tests against a tagged executor (e.g. before I push the docker image to docker hub).

**Comment by FlorianGrundig** [comment]
The problem is that our scheduler defines (hard coded) which executor version it should start to ensure compatible versions. For a git release (tagging logstash framework e.g. as 0.1.0)  I want to specify the version because latest is not appropriate anymore. But as soon as I do that the system tests are failing. That means if someone checks out the logstash-framework in a specific version the system tests are failing...
