### ISSUE TITLE
Unable to query containers and kill executors on mesos-local when not on linux

### ISSUE THREAD

**Issue by philwinder** [ContainerSolutions/mini-mesos#47]
https://github.com/ContainerSolutions/mini-mesos/blob/master/src/main/java/org/apache/mesos/mini/mesos/MesosContainer.java#L83

This line communicates directly with the docker daemon on mesos-local. Because Mac users are using docker-machine, this traffic needs to be proxied through docker machine.

See https://github.com/mesos/elasticsearch/blob/master/system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/ExecutorSystemTest.java#L52
for an example

**Comment by frankscholten** [comment]
Obsolete
